/**
 * Generates `mapinfo.lua`.
 *
 * The output follows the skeleton every BAR map uses, and it follows it for
 * concrete reasons rather than cargo cult:
 *
 *  1. `local mapinfo = { ... }` is the **first statement**, containing only
 *     literals. BAR's `map-parser` reads the file statically with `luaparse`
 *     and takes the first table constructor; a computed value there is
 *     invisible to the map pipeline.
 *  2. `lowerkeys(mapinfo)` runs afterwards, because the engine lowercases keys
 *     itself but game-side `VFS.Include("mapinfo.lua")` does not.
 *  3. The `mapconfig/mapinfo/*.lua` merge block gives the map working map
 *     options (water level, terrain speed presets) without the author writing
 *     any Lua.
 */

import { LuaIndexedTable, toLua, type LuaTable, type LuaValue } from './lua.js';
import type { MapInfo, TeamStart, TerrainType } from './types.js';

const HEADER = `--------------------------------------------------------------------------------
-- mapinfo.lua  --  generated by Terrasmith
--
-- \`local mapinfo = { ... }\` must stay the first statement in this file and must
-- contain only literals: BAR's maps-metadata tooling parses it statically and
-- never executes it.
--------------------------------------------------------------------------------
`;

const FOOTER = `
--------------------------------------------------------------------------------
-- Lowercase every string key, recursively. The engine does this itself, but
-- game-side VFS.Include("mapinfo.lua") does not, and BAR gadgets read
-- mapinfo.voidwater, mapinfo.custom.grassconfig and friends.
--------------------------------------------------------------------------------
local function lowerkeys(ta)
\tlocal fix = {}
\tfor i, v in pairs(ta) do
\t\tif type(i) == "string" and i ~= i:lower() then
\t\t\tfix[#fix + 1] = i
\t\tend
\t\tif type(v) == "table" then
\t\t\tlowerkeys(v)
\t\tend
\tend
\tfor i = 1, #fix do
\t\tlocal idx = fix[i]
\t\tta[idx:lower()] = ta[idx]
\t\tta[idx] = nil
\tend
end

lowerkeys(mapinfo)

--------------------------------------------------------------------------------
-- Merge every mapconfig/mapinfo/*.lua (sorted) into \`mapinfo\`. Those files may
-- mutate the exposed \`mapinfo\` global and/or return a table to deep-merge.
-- They see LOWERCASED keys, because lowerkeys already ran.
--------------------------------------------------------------------------------
if (Spring) then
\tlocal function tmerge(t1, t2)
\t\tfor i, v in pairs(t2) do
\t\t\tif type(v) == "table" then
\t\t\t\tt1[i] = t1[i] or {}
\t\t\t\ttmerge(t1[i], v)
\t\t\telse
\t\t\t\tt1[i] = v
\t\t\tend
\t\tend
\tend

\t-- Spring.GetMapOptions is absent in unitsync, dedicated and AI builds.
\tif (not Spring.GetMapOptions) then
\t\tSpring.GetMapOptions = function() return {} end
\tend

\tfunction tobool(val)
\t\tlocal t = type(val)
\t\tif t == "nil" then return false
\t\telseif t == "boolean" then return val
\t\telseif t == "number" then return (val ~= 0)
\t\telseif t == "string" then return ((val ~= "0") and (val ~= "false")) end
\t\treturn false
\tend

\tgetfenv()["mapinfo"] = mapinfo
\t\tlocal files = VFS.DirList("mapconfig/mapinfo/", "*.lua")
\t\ttable.sort(files)
\t\tfor i = 1, #files do
\t\t\tlocal newcfg = VFS.Include(files[i])
\t\t\tif newcfg then
\t\t\t\tlowerkeys(newcfg)
\t\t\t\ttmerge(mapinfo, newcfg)
\t\t\tend
\t\tend
\tgetfenv()["mapinfo"] = nil
end

return mapinfo
`;

/** The companion file BAR maps ship for engine versions <= 0.82. */
export const MAPHELPER_MAPINFO_LUA = 'return VFS.Include("mapinfo.lua")\n';

/** Render a `MapInfo` as the text of a `mapinfo.lua` file. */
export function writeMapInfoLua(info: MapInfo): string {
  const table = toLuaTable(info);
  return `${HEADER}\nlocal mapinfo = ${toLua(table)}\n${FOOTER}`;
}

/**
 * Convert the typed model into the shape the serialiser wants, mainly by
 * turning the 0-based `teams` and `terrainTypes` records into explicit
 * `[n] = ...` tables.
 */
function toLuaTable(info: MapInfo): LuaTable {
  const out: LuaTable = {};
  const copy = <K extends keyof MapInfo>(key: K): void => {
    const v = info[key];
    if (v !== undefined) out[key as string] = v as LuaValue;
  };

  // Order matters only for readability, but a stable order makes diffs between
  // two builds of the same map meaningful.
  copy('name');
  copy('shortname');
  copy('description');
  copy('author');
  copy('version');
  copy('mapfile');
  copy('modtype');
  copy('depend');
  copy('replace');

  copy('maphardness');
  copy('notDeformable');
  copy('gravity');
  copy('tidalStrength');
  copy('maxMetal');
  copy('extractorRadius');
  copy('voidWater');
  copy('voidGround');
  copy('voidAlphaMin');
  copy('autoShowMetal');

  copy('smf');
  copy('sound');
  copy('resources');
  copy('splats');
  copy('atmosphere');
  copy('grass');
  copy('lighting');
  copy('water');

  if (info.teams) out.teams = teamsTable(info.teams);
  if (info.terrainTypes) out.terrainTypes = terrainTypesTable(info.terrainTypes);
  copy('pfs');
  if (info.custom) out.custom = info.custom as LuaValue;

  return out;
}

function teamsTable(teams: Record<number, TeamStart>): LuaIndexedTable {
  const keys = Object.keys(teams)
    .map(Number)
    .sort((a, b) => a - b);
  return new LuaIndexedTable(
    keys.map((k) => [k, { startPos: { x: teams[k].startPos.x, z: teams[k].startPos.z } }] as const),
  );
}

function terrainTypesTable(types: Record<number, TerrainType>): LuaIndexedTable {
  const keys = Object.keys(types)
    .map(Number)
    .sort((a, b) => a - b);
  return new LuaIndexedTable(keys.map((k) => [k, types[k] as unknown as LuaValue] as const));
}

/**
 * Check a `MapInfo` for the mistakes that produce a map the engine loads but
 * renders wrong — the kind that are invisible until someone opens the map in
 * game and asks why it looks flat.
 */
export function collectMapInfoProblems(info: MapInfo): string[] {
  const p: string[] = [];
  if (!info.name || info.name.trim() === '') {
    p.push('name is required; the lobby shows it and the archive scanner keys on it');
  }
  if (info.modtype !== undefined && info.modtype !== 3) {
    p.push(`modtype should be 3 for a map, got ${info.modtype}`);
  }
  if (!info.mapfile) {
    p.push('mapfile is unset; the engine will fall back to scanning the archive for a .smf');
  }

  const res = info.resources;
  if (res) {
    const advanced = [
      res.splatDistrTex,
      res.splatDetailNormalTex1,
      res.detailNormalTex,
      res.lightEmissionTex,
      res.parallaxHeightTex,
      res.skyReflectModTex,
    ].some(Boolean);
    if (advanced && !res.specularTex) {
      p.push(
        'specularTex is unset, so the engine uses basic shading and ignores the splat, ' +
          'normal and emission textures this map declares',
      );
    }
    const usesDnts = Boolean(res.splatDetailNormalTex1);
    if (usesDnts && !res.splatDetailTex) {
      p.push(
        'splatDetailTex must be a non-empty string for splatting to activate, even when ' +
          'detail-normal textures are used and the file does not exist',
      );
    }
    if ((res.splatDistrTex && !usesDnts && !res.splatDetailTex) ||
        (res.splatDetailTex && !res.splatDistrTex && !usesDnts)) {
      p.push('classic splatting needs both splatDetailTex and splatDistrTex; only one is set');
    }
  }

  if (info.smf?.minheight !== undefined && info.smf?.maxheight !== undefined) {
    if (info.smf.maxheight <= info.smf.minheight) {
      p.push(`smf.maxheight (${info.smf.maxheight}) must exceed smf.minheight (${info.smf.minheight})`);
    }
  }

  if (info.teams) {
    const keys = Object.keys(info.teams).map(Number).sort((a, b) => a - b);
    for (let i = 0; i < keys.length; i++) {
      if (keys[i] !== i) {
        p.push(`teams keys must start at 0 and be contiguous; found ${keys.join(', ')}`);
        break;
      }
    }
  }

  if (info.terrainTypes) {
    for (const key of Object.keys(info.terrainTypes).map(Number)) {
      if (!Number.isInteger(key) || key < 0 || key > 255) {
        p.push(`terrainTypes index ${key} is outside the 0..255 typemap range`);
      }
    }
  }

  return p;
}
